name: Practice Workflow
on: push

jobs:
  run_black_job:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v3
      - run: |
          pip install black
          make black

  run_flake8_job:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v3
      - run: |
          pip install flake8
          make flake8

  run_pylint_job:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v3
      - run: |
          pip install pylint
          make pylint
