name: Practice Workflow
on: push

jobs:
  run_black_job:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v3
      - run: |
          pip install black
          black --check .

  run_flake8_job:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v3
      - run: |
          pip install flake8
          flake8 --check .

  run_pylint_job:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v3
      - run: |
          pip install pylint
          pylint --check .
